### ISSUE TITLE
Remove links to delete processed ADOs for update AMI sets

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#67] opened 2022-03-15 19:50 UTC
If you cannot delete processed ADOs because the AMI set is configured as an update set, you should not be presented with links to do so. 

This was prompted when we found that one of our contrib modules was whitescreening because it was trying to do a form alter on the delete processed ADOs confirmation page when there was no form to display. That is solved having \Drupal\ami\Form\amiSetEntityDeleteProcessedForm::buildForm return a proper form, rather than just a bit of a render array.

But the main issue is that we should not see the links to delete processed ADOs in the first place when the AMI set is "update". These links appear in the operations column of `/amiset/list`, as well as a in the menu tabs when viewing an individual AMI set.

The operations links are controlled here: [\Drupal\ami\Entity\Controller\amiSetEntityListBuilder::getOperations](https://github.com/esmero/ami/blob/0.3.0/src/Entity/Controller/amiSetEntityListBuilder.php#L65)
The menu tabs are access-controlled here: [\Drupal\ami\Entity\Controller\amiSetEntityAccessControlHandler::checkAccess](https://github.com/esmero/ami/blob/0.3.0/src/Entity/Controller/amiSetEntityAccessControlHandler.php#L17)

I will have a proposed PR to address these things shortly.

**Comment by DiegoPino** [comment] 2022-03-15 19:55
@patdunlavey ok I get this, but this does not white-screen in this module right? re: https://github.com/esmero/ami/commit/6d605cc6591a46f7bc09cb9aa7b6e08c05e0cac7 So you can check on your contributed one if the alter you want to alter actually exists? The issue is that it adds a lot of over processing on the actual listing (the AMI set lists / ::getOperations) because we have go access every AMI set and parse its JSON. Is this really really needed?

**Comment by patdunlavey** [comment] 2022-03-15 19:56
Cache for performance?

**Comment by DiegoPino** [comment] 2022-03-15 19:57
Cache might be a good option if you can invalidate the cache on every entity save/update

**Comment by patdunlavey** [comment] 2022-03-15 20:02
Shhh!!

**Comment by patdunlavey** [comment] 2022-03-15 21:44
PR Created: https://github.com/esmero/ami/pull/68

**Comment by DiegoPino** [comment] 2022-04-15 21:29
Resolved via https://github.com/esmero/ami/commit/65af48a57e8b24959aaa6fab6aa618ed5357fae6
Thanks @patdunlavey and sorry for the delay on merging

**Closed by DiegoPino** 2022-04-15 21:29 UTC
Labels: enhancement, UI, Ingest Setup
